### ISSUE TITLE
Use http_build_query

### ISSUE THREAD

**Issue by lionser** [eightalex/catnap#19]
https://github.com/eightalex/yousleep/blob/21f686dab833c1f6d8db775473a7b41db6eea4b9/src/Controller/OrderController.php#L79

`chat_id=$chatId&text=$message`
To:
```
http_build_query([
   'chat_id' => $chatId,
   'text' => $message
]);
```
Сохраняй читабельность

**Comment by eightalex** [comment]
Спасибо вам большое, уважаемый Сергей!
